[env:nano_33_iot_BUILD]
platform = atmelsam
board = nano_33_iot
framework = arduino
build_flags = 
  -I src/Arduino/
  -I src/Arduino/GetMeasureData/
  -I src/Arduino/MetalDetector/
  -I src/Calculations/
  -I src/Optimizations/
build_src_filter =
  +<Arduino/*.h>
  +<Arduino/*.cpp>
  +<Arduino/GetMeasureData/*.h>
  +<Arduino/GetMeasureData/*.cpp>
  +<Arduino/MetalDetector/*.h>
  +<Arduino/MetalDetector/*.cpp>
  +<Calculations/*.h>
  +<Calculations/*.cpp>
  +<Optimizations/*.h>
  +<Optimizations/*.cpp>

[env:nano_33_iot_SIMULATE_SENSORS]
platform = atmelsam
board = nano_33_iot
framework = arduino
build_flags = 
  -I src/Arduino/
  -I src/Arduino/GetMeasureData/
  -I src/Arduino/MetalDetectorSimulations/
  -I src/Simulations/
  -I src/Calculations/
  -I src/Optimizations/
build_src_filter =
  +<Arduino/*.h>
  +<Arduino/*.cpp>
  +<Arduino/GetMeasureData/*.h>
  +<Arduino/GetMeasureData/*.cpp>
  +<Arduino/MetalDetectorSimulations/*.h>
  +<Arduino/MetalDetectorSimulations/*.cpp>
  +<Simulations/*.h>
  +<Simulations/*.cpp>
  +<Calculations/*.h>
  +<Calculations/*.cpp>
  +<Optimizations/*.h>
  +<Optimizations/*.cpp>

[env:nano_33_iot_SIMULATE_MEASUREDATA]
platform = atmelsam
board = nano_33_iot
framework = arduino
build_flags = 
  -I src/Arduino/
  -I src/Arduino/GetMeasureDataSimulations/
  -I src/Simulations/
  -I src/Calculations/
  -I src/Optimizations/
build_src_filter =
  +<Arduino/*.h>
  +<Arduino/*.cpp>
  +<Arduino/GetMeasureDataSimulations/*.h>
  +<Arduino/GetMeasureDataSimulations/*.cpp>
  +<Simulations/*.h>
  +<Simulations/*.cpp>
  +<Calculations/*.h>
  +<Calculations/*.cpp>
  +<Optimizations/*.h>
  +<Optimizations/*.cpp>

[env:Native_SingleThreaded_SIMULATION_DATA]
platform = native
build_flags = 
  -I src/Native/
  -I src/Native/Output/
  -I src/Native/SingleThreaded/
  -I src/Simulations/
  -I src/Calculations/
  -I src/Optimizations/
build_src_filter =
  +<Native/*.h>
  +<Native/*.cpp>
  +<Native/Output/*.h>
  +<Native/Output/*.cpp>
  +<Native/SingleThreaded/*.h>
  +<Native/SingleThreaded/*.cpp>
  +<Simulations/*.h>
  +<Simulations/*.cpp>
  +<Calculations/*.h>
  +<Calculations/*.cpp>
  +<Optimizations/*.h>
  +<Optimizations/*.cpp>

[env:Native_MultiThreaded_SIMULATION_DATA]
platform = native
build_flags = 
  -I src/Native/
  -I src/Native/Output/
  -I src/Native/MultiThreaded/
  -I src/Simulations/
  -I src/Calculations/
  -I src/Optimizations/
build_src_filter =
  +<Native/*.h>
  +<Native/*.cpp>
  +<Native/Output/*.h>
  +<Native/Output/*.cpp>
  +<Native/MultiThreaded/*.h>
  +<Native/MultiThreaded/*.cpp>
  +<Simulations/*.h>
  +<Simulations/*.cpp>
  +<Calculations/*.h>
  +<Calculations/*.cpp>
  +<Optimizations/*.h>
  +<Optimizations/*.cpp>

#[env:Native_MultiThreadedReworked_SIMULATION_DATA]
#platform = native
#build_flags = 
#  -I src/Native/
#  -I src/Native/MultiThreadedReworked/
#  -I src/Simulations/
#  -I src/Calculations/
#  -I src/Optimizations/
#build_src_filter =
#  +<Native/*.h>
#  +<Native/*.cpp>
#  +<Native/MultiThreadedReworked/*.h>
#  +<Native/MultiThreadedReworked/*.cpp>
#  +<Simulations/*.h>
#  +<Simulations/*.cpp>
#  +<Calculations/*.h>
#  +<Calculations/*.cpp>
#  +<Optimizations/*.h>
#  +<Optimizations/*.cpp>