#ifndef CALCULATEMEASUREDATA_H
#define CALCULATEMEASUREDATA_H

#include <cmath>

#include "SimulationData.h"
#include "MeasureData.h"
#include "Transformations.h"
#include "FastTrigonometry.h"

// calculates the measurement data that would be generated by the piece passing by the sensors,
// based on the piece's properties and the sensor positions
// the output is stored in the provided MeasureData struct, which should be initialized with the correct count and allocated sensorData array
void calculateMeasurementData(MeasureData* data, bool* enabled, Piece piece);

#endif